### ISSUE TITLE
Can not pip install

### ISSUE THREAD

**Issue by kthibodeaux** [ensky/taiga-contrib-ldap-auth#10]
This is on a fresh Ubuntu 14.04 system with Taiga installed from the taiga-scripts repository

```
Downloading/unpacking taiga-contrib-ldap-auth
  Getting page https://pypi.python.org/simple/taiga-contrib-ldap-auth/
  URLs to search for versions for taiga-contrib-ldap-auth:
  * https://pypi.python.org/simple/taiga-contrib-ldap-auth/
  Analyzing links from page https://pypi.python.org/simple/taiga-contrib-ldap-auth/
    Found link https://pypi.python.org/packages/source/t/taiga-contrib-ldap-auth/taiga-contrib-ldap-auth-0.0.2.tar.gz#md5=bff7ad94a8f6168abeef7655e19b8acb (from https://pypi.python.org/simple/taiga-contrib-ldap-auth/), version: 0.0.2
    Found link https://pypi.python.org/packages/source/t/taiga-contrib-ldap-auth/taiga-contrib-ldap-auth-0.0.3.tar.gz#md5=015fd2c6b90cdda0a008b6ff43c38c3a (from https://pypi.python.org/simple/taiga-contrib-ldap-auth/), version: 0.0.3
  Using version 0.0.3 (newest of versions: 0.0.3, 0.0.2)
  Downloading taiga-contrib-ldap-auth-0.0.3.tar.gz
  Downloading from URL https://pypi.python.org/packages/source/t/taiga-contrib-ldap-auth/taiga-contrib-ldap-auth-0.0.3.tar.gz#md5=015fd2c6b90cdda0a008b6ff43c38c3a (from https://pypi.python.org/simple/taiga-contrib-ldap-auth/)
  Running setup.py (path:/tmp/pip_build_deploy/taiga-contrib-ldap-auth/setup.py) egg_info for package taiga-contrib-ldap-auth

    Installed /tmp/pip_build_deploy/taiga-contrib-ldap-auth/versiontools-1.9.1-py2.7.egg
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip_build_deploy/taiga-contrib-ldap-auth/setup.py", line 33, in <module>
        'Topic :: Internet :: WWW/HTTP',
      File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 243, in __init__
        _Distribution.__init__(self,attrs)
      File "/usr/lib/python2.7/distutils/dist.py", line 287, in __init__
        self.finalize_options()
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 277, in finalize_options
        ep.load()(self, ep.name, value)
      File "build/bdist.linux-x86_64/egg/versiontools/setuptools_hooks.py", line 64, in version
      File "build/bdist.linux-x86_64/egg/versiontools/__init__.py", line 234, in from_expression
      File "taiga_contrib_ldap_auth/__init__.py", line 2
    SyntaxError: Non-ASCII character '\xc3' in file taiga_contrib_ldap_auth/__init__.py on line 2, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details
    Complete output from command python setup.py egg_info:
    Installed /tmp/pip_build_deploy/taiga-contrib-ldap-auth/versiontools-1.9.1-py2.7.egg
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip_build_deploy/taiga-contrib-ldap-auth/setup.py", line 33, in <module>
        'Topic :: Internet :: WWW/HTTP',
      File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 243, in __init__
        _Distribution.__init__(self,attrs)
      File "/usr/lib/python2.7/distutils/dist.py", line 287, in __init__
        self.finalize_options()
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 277, in finalize_options
        ep.load()(self, ep.name, value)
      File "build/bdist.linux-x86_64/egg/versiontools/setuptools_hooks.py", line 64, in version
      File "build/bdist.linux-x86_64/egg/versiontools/__init__.py", line 234, in from_expression
      File "taiga_contrib_ldap_auth/__init__.py", line 2
    SyntaxError: Non-ASCII character '\xc3' in file taiga_contrib_ldap_auth/__init__.py on line 2, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details
    Complete output from command python setup.py egg_info:


Installed /tmp/pip_build_deploy/taiga-contrib-ldap-auth/versiontools-1.9.1-py2.7.egg

Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip_build_deploy/taiga-contrib-ldap-auth/setup.py", line 33, in <module>

    'Topic :: Internet :: WWW/HTTP',

  File "/usr/lib/python2.7/distutils/core.py", line 111, in setup

    _setup_distribution = dist = klass(attrs)

  File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 243, in __init__

    _Distribution.__init__(self,attrs)

  File "/usr/lib/python2.7/distutils/dist.py", line 287, in __init__

    self.finalize_options()

  File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 277, in finalize_options

    ep.load()(self, ep.name, value)

  File "build/bdist.linux-x86_64/egg/versiontools/setuptools_hooks.py", line 64, in version

  File "build/bdist.linux-x86_64/egg/versiontools/__init__.py", line 234, in from_expression

  File "taiga_contrib_ldap_auth/__init__.py", line 2

SyntaxError: Non-ASCII character '\xc3' in file taiga_contrib_ldap_auth/__init__.py on line 2, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details

----------------------------------------
Cleaning up...
  Removing temporary dir /tmp/pip_build_deploy...
Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_deploy/taiga-contrib-ldap-auth
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1229, in prepare_files
    req_to_install.run_egg_info()
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 325, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/usr/lib/python2.7/dist-packages/pip/util.py", line 697, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_deploy/taiga-contrib-ldap-auth
```

**Comment by ensky** [comment]
Try to use python 3 rather than 2.7.
Taiga doesn't support python 2.7

**Comment by kthibodeaux** [comment]
Thank you, I took a peak through the Taiga install script and it seems it uses a different Python install than system.  All is well now :)
