### ISSUE TITLE
Unable to install ldap.com unreachable

### ISSUE THREAD

**Issue by fanch317** [ensky/taiga-contrib-ldap-auth#11]
The contrib could not be installed.

The URL used by setup.py ( https://ldap.com/taigaio/taiga-contrib-ldap-auth ) forward on www.unboundid.com. So files can be loaded.

There are a alternative to this URL ?

```
Downloading/unpacking taiga-contrib-ldap-auth
  Downloading taiga-contrib-ldap-auth-0.0.4.tar.gz
  Running setup.py (path:/tmp/pip-build-7y064M/taiga-contrib-ldap-auth/setup.py) egg_info for package taiga-contrib-ldap-auth

    Installed /tmp/pip-build-7y064M/taiga-contrib-ldap-auth/versiontools-1.9.1-py2.7.egg
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip-build-7y064M/taiga-contrib-ldap-auth/setup.py", line 34, in <module>
        'Topic :: Internet :: WWW/HTTP',
      File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 266, in __init__
        _Distribution.__init__(self,attrs)
      File "/usr/lib/python2.7/distutils/dist.py", line 287, in __init__
        self.finalize_options()
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 301, in finalize_options
        ep.load()(self, ep.name, value)
      File "build/bdist.linux-x86_64/egg/versiontools/setuptools_hooks.py", line 64, in version
      File "build/bdist.linux-x86_64/egg/versiontools/__init__.py", line 234, in from_expression
      File "taiga_contrib_ldap_auth/__init__.py", line 2
    SyntaxError: Non-ASCII character '\xc3' in file taiga_contrib_ldap_auth/__init__.py on line 2, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
    Complete output from command python setup.py egg_info:


Installed /tmp/pip-build-7y064M/taiga-contrib-ldap-auth/versiontools-1.9.1-py2.7.egg

Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip-build-7y064M/taiga-contrib-ldap-auth/setup.py", line 34, in <module>

    'Topic :: Internet :: WWW/HTTP',

  File "/usr/lib/python2.7/distutils/core.py", line 111, in setup

    _setup_distribution = dist = klass(attrs)

  File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 266, in __init__

    _Distribution.__init__(self,attrs)

  File "/usr/lib/python2.7/distutils/dist.py", line 287, in __init__

    self.finalize_options()

  File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 301, in finalize_options

    ep.load()(self, ep.name, value)

  File "build/bdist.linux-x86_64/egg/versiontools/setuptools_hooks.py", line 64, in version

  File "build/bdist.linux-x86_64/egg/versiontools/__init__.py", line 234, in from_expression

  File "taiga_contrib_ldap_auth/__init__.py", line 2

SyntaxError: Non-ASCII character '\xc3' in file taiga_contrib_ldap_auth/__init__.py on line 2, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-7y064M/taiga-contrib-ldap-auth
Storing debug log for failure in /root/.pip/pip.log
```

**Comment by ensky** [comment]
it seems that duplicate #10
try to use python 3 rather than python 2.7

**Comment by jolinx** [comment]
sudo pip3 install taiga-contrib-ldap-auth
