### ISSUE TITLE
Plugin not compatible with Taiga 2.0.0

### ISSUE THREAD

**Issue by schobelthoma** [ensky/taiga-contrib-ldap-auth#29]
After upgrading Taiga to 2.0.0 LDAP Plugin breaks taiga:

Trying import local.py settings...
Trying import local.py settings...
Trying import local.py settings...
Traceback (most recent call last):
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/gunicorn/arbiter.py", line 184, in run
    self.sleep()
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/gunicorn/arbiter.py", line 317, in sleep
    ready = select.select([self.PIPE[0]], [], [], 1.0)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/gunicorn/arbiter.py", line 219, in handle_chld
    self.reap_workers()
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/gunicorn/arbiter.py", line 464, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/taiga/.virtualenvs/taiga/bin/gunicorn", line 11, in <module>
    sys.exit(run())
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/gunicorn/app/wsgiapp.py", line 74, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/gunicorn/app/base.py", line 192, in run
    super(Application, self).run()
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/gunicorn/arbiter.py", line 206, in run
    self.halt(reason=inst.reason, exit_status=inst.exit_status)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/gunicorn/arbiter.py", line 302, in halt
    self.stop()
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/gunicorn/arbiter.py", line 347, in stop
    time.sleep(0.1)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/gunicorn/arbiter.py", line 219, in handle_chld
    self.reap_workers()
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/gunicorn/arbiter.py", line 464, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>

**Comment by orthagh** [comment]
Moving theses lines https://github.com/ensky/taiga-contrib-ldap-auth/blob/master/taiga_contrib_ldap_auth/apps.py#L20-L21  

after 'def ready' seems to fix the issue

**Comment by schobelthoma** [comment]
Hi orthagh,
did this fix it for you? For me it didn´t help....
Cheers

**Comment by schobelthoma** [comment]
Fixed with https://github.com/ensky/taiga-contrib-ldap-auth/issues/30

**Comment by schobelthoma** [comment]
Fixed with https://github.com/ensky/taiga-contrib-ldap-auth/issues/30

**Comment by elentar** [comment]
This requires the fix for #30 AND ALSO to remove "taiga-contrib-ldap-auth" from the list of contribPlugins. With it in there, you'll get a white screen on any page you try to load. With it removed, LDAP auth works as does everything else.

**Comment by ensky** [comment]
I've updated this plugin to 0.1 with your PR included.
@zeroslash can u help to verify if this plugin works fine in version 0.1?
Thanks, and sorry for late reply, I'm not using taiga for a while.

**Comment by martin-sa** [comment]
For what it is worth, I've installed Taiga 1.10.0 with  9f2170c of taiga-contrib-ldap-auth. It was possible to login successfully without encountering any problems.

**Comment by flyingcircle** [comment]
I have not seen any issue with "taiga-contrib-ldap-auth" being in the contribPlugins. Is it possible that you had a typo somewhere?

**Comment by flyingcircle** [comment]
adding "taiga-contrib-ldap-auth" to the contribPlugins was never part of the install instructions, and is an unrelated issue to this one.
