### ISSUE TITLE
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.

### ISSUE THREAD

**Issue by voidpp** [ensky/taiga-contrib-ldap-auth#32]
When I try to run the taiga backend:

```
(taiga)taiga@taiga:~/taiga-back$ python manage.py runserver
Trying import local.py settings...
Trying import local.py settings...
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7f03ed313400>
Traceback (most recent call last):
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/core/management/commands/runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/utils/autoreload.py", line 249, in raise_last_exception
    six.reraise(*_exception)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/apps/config.py", line 116, in create
    mod = import_module(mod_path)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/taiga_contrib_ldap_auth/apps.py", line 20, in <module>
    from taiga.auth.services import register_auth_plugin
  File "/home/taiga/taiga-back/taiga/auth/services.py", line 34, in <module>
    from taiga.base.mails import mail_builder
  File "/home/taiga/taiga-back/taiga/base/mails.py", line 20, in <module>
    from djmail import template_mail
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/djmail/template_mail.py", line 14, in <module>
    from . import models
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/djmail/models.py", line 24, in <module>
    class Message(models.Model):
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/db/models/base.py", line 94, in __new__
    app_config = apps.get_containing_app_config(module)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/apps/registry.py", line 239, in get_containing_app_config
    self.check_apps_ready()
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/apps/registry.py", line 124, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.
```

Content of `settings/local.py`

``` py
from .common import *

MEDIA_URL = "http://taiga.company/media/"
STATIC_URL = "http://taiga.company/static/"
ADMIN_MEDIA_PREFIX = "http://taiga.company/static/admin/"
SITES["front"]["scheme"] = "http"
SITES["front"]["domain"] = "taiga.company"

SECRET_KEY = "theveryultratopsecretkey42"

DEBUG = False
TEMPLATE_DEBUG = False
PUBLIC_REGISTER_ENABLED = True

DEFAULT_FROM_EMAIL = "no-reply@taiga.company"
SERVER_EMAIL = DEFAULT_FROM_EMAIL

# Uncomment and populate with proper connection parameters
# for enable email sending. EMAIL_HOST_USER should end by @domain.tld
#EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
#EMAIL_USE_TLS = False
#EMAIL_HOST = "localhost"
#EMAIL_HOST_USER = ""
#EMAIL_HOST_PASSWORD = ""
#EMAIL_PORT = 25

# Uncomment and populate with proper connection parameters
# for enable github login/singin.
#GITHUB_API_CLIENT_ID = "yourgithubclientid"
#GITHUB_API_CLIENT_SECRET = "yourgithubclientsecret"



INSTALLED_APPS += ["taiga_contrib_ldap_auth"]

LDAP_SERVER = 'ldap://10.10.0.2'
LDAP_PORT = 389

# Full DN of the service account use to connect to LDAP server and search for login user's account entry
# If LDAP_BIND_DN is not specified, or is blank, then an anonymous bind is attempated
LDAP_BIND_DN = 'cn=Manager,dc=company,dc=com'
LDAP_BIND_PASSWORD = '42'   # eg.
# Starting point within LDAP structure to search for login user
LDAP_SEARCH_BASE = 'ou=People,dc=company,dc=com'
# LDAP property used for searching, ie. login username needs to match value in sAMAccountName property in LDAP
LDAP_SEARCH_PROPERTY = 'sAMAccountName'
LDAP_SEARCH_SUFFIX = None # '@example.com'

# Names of LDAP properties on user account to get email and full name
LDAP_EMAIL_PROPERTY = 'mail'
LDAP_FULL_NAME_PROPERTY = 'name'
```

``` bash
(taiga)taiga@taiga:~/taiga-back$ pip list
amqp (1.4.9)
anyjson (0.3.3)
billiard (3.3.0.23)
bleach (1.4.2)
celery (3.1.20)
contextlib2 (0.5.1)
cssselect (0.9.1)
cssutils (1.0.1)
diff-match-patch (20121119)
Django (1.9.5)
django-ipware (1.1.3)
django-jinja (2.1.2)
django-pgjson (0.3.1)
django-pglocks (1.0.2)
django-picklefield (0.3.2)
django-sampledatahelper (0.4)
django-sites (0.9)
django-sr (0.0.4)
djmail (0.12.0-1)
djorm-pgarray (1.2)
easy-thumbnails (2.3)
fn (0.4.3)
future (0.15.2)
gunicorn (19.4.5)
html5lib (0.9999999)
Jinja2 (2.8)
kombu (3.0.35)
ldap3 (1.2.2)
lxml (3.5.0)
Markdown (2.6.5)
MarkupSafe (0.23)
netaddr (0.7.18)
Pillow (3.1.1)
pip (1.5.4)
premailer (2.9.7)
psycopg2 (2.6.1)
pyasn1 (0.1.9)
pycryptodome (3.4)
Pygments (2.0.2)
pyjwkest (1.1.5)
python-dateutil (2.4.2)
pytz (2015.7)
raven (5.10.2)
redis (2.10.5)
requests (2.9.1)
sampledata (0.3.7)
setuptools (2.2)
six (1.10.0)
taiga-contrib-ldap-auth (0.0.6)
Unidecode (0.04.19)
```

Without the ldap config the taiga is working well.

**Comment by Kegeruneku** [comment]
Please look at https://github.com/ensky/taiga-contrib-ldap-auth/pull/30 for a solution :)

**Comment by voidpp** [comment]
Thx, it helped. As I see, there is an open PR about this, so I close this issue.
