### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by thierryfrch** [ensky/taiga-contrib-ldap-auth#60]
Hello,

just upgraded pip to install ldap-auth but the installation failed:

root@virt-taiga:/tmp# pip install taiga-contrib-ldap-auth
Collecting taiga-contrib-ldap-auth
  Using cached taiga-contrib-ldap-auth-0.1.1.tar.gz
    Complete output from command python setup.py egg_info:

    Installed /tmp/pip-build-DhIBrd/taiga-contrib-ldap-auth/.eggs/versiontools-1.9.1-py2.7.egg
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-DhIBrd/taiga-contrib-ldap-auth/setup.py", line 34, in <module>
        'Topic :: Internet :: WWW/HTTP',
      File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 272, in __init__
        _Distribution.__init__(self,attrs)
      File "/usr/lib/python2.7/distutils/dist.py", line 287, in __init__
        self.finalize_options()
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 327, in finalize_options
        ep.load()(self, ep.name, value)
      File "build/bdist.linux-x86_64/egg/versiontools/setuptools_hooks.py", line 64, in version
      File "build/bdist.linux-x86_64/egg/versiontools/__init__.py", line 234, in from_expression
      File "/tmp/pip-build-DhIBrd/taiga-contrib-ldap-auth/taiga_contrib_ldap_auth/__init__.py", line 2
    SyntaxError: Non-ASCII character '\xc3' in file /tmp/pip-build-DhIBrd/taiga-contrib-ldap-auth/taiga_contrib_ldap_auth/__init__.py on line 2, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-DhIBrd/taiga-contrib-ldap-auth/

Is someone able to help me to fix this issue ?

Thank you !

Thierry

**Comment by phanikumar1210** [comment]
I had the same issue and the reason is by default pip might use python2.7. But you need to update the pip to use python3 to get the installation successful

**Comment by thierryfrch** [comment]
Super thanks ! I’ll try it out tomorrow !



*Thierry FRACHE*

Responsable technique

Mobile : +33 (0)7 84 28 73 07
thierry.frache@hexawin.fr

[image: LOGO-HEXAWIN][image:
http://www.hexawin.fr/wp-content/uploads/2018/01/icFacebook.png]
<https://www.facebook.com/Hexawin/> [image:
http://www.hexawin.fr/wp-content/uploads/2018/01/icoLinkedin.png]
<https://www.linkedin.com/company/hexawin/>

*Nos agences dans l’Hexagone *(*Montpellier* – Avignon – Aix-en-Provence –
Toulouse)



*From:* phanikumar1210 [mailto:notifications@github.com]
*Sent:* Wednesday, April 25, 2018 6:20 PM
*To:* ensky/taiga-contrib-ldap-auth <
taiga-contrib-ldap-auth@noreply.github.com>
*Cc:* thierryfrch <thierry.frache@hexawin.fr>; Author <
author@noreply.github.com>
*Subject:* Re: [ensky/taiga-contrib-ldap-auth] Unable to install (#60)



I had the same issue and the reason is by default pip might use python2.7.
But you need to update the pip to use python3 to get the installation
successful

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ensky/taiga-contrib-ldap-auth/issues/60#issuecomment-384346408>,
or mute the thread
